# main text of home
name: Gal Nagli
bio: Published Bug Bounty Writeups
# twitter summary info
description: My online portfolio
# if it's an external image, update below for true
# better with square images
external-image: true
picture: /assets/images/cartoon_profile.png
url: https://galnagli.com
# your url: https://USERNAME.github.io
permalink: /:title/
# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'
# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1
# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: mydisqus # enter this from your disqus account
  categories: [blog, project] # only show disqus for posts that have these categories
# if you don't have any of social below, comment the line
#twitter: naglinagli
#linkedin: galnagli
#github: naglinagli
github: naglinagli

authors:
  galnagli:
@@ -96,9 +96,6 @@ plugins:
  - jekyll-admin
  - jekyll-paginate-v2

jekyll-mentions:
  base_url: https://github.com

compress_html:
  ignore:
    envs:
      - development
      - stage
exclude:
  [
    "travis.sh",
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "FAQ.md",
    "node_modules",
    "vendor",
  ]
